name: Deploy to ec2
on:
  push:
    branches:
      - main
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build and tag Docker image 
      run: |
        docker build -t jerrywise97/periodapp .
     
    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push jerrywise97/periodapp:latest
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S }}
          aws-region: us-east-1
          
    - name: Add EC2 private key to SSH agent
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/key-air.pem
          chmod 400 ~/.ssh/key-air.pem
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/key-air.pem

    - name: Connect to EC2 instance and deploy
      run: |
          ssh-keyscan -H 54.157.140.149 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker stop periodapp || true && sudo docker rm -f periodapp || true'
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker pull jerrywise97/periodapp:latest'
          ssh -i ~/.ssh/key-air.pem ec2-user@54.157.140.149 'sudo docker run -d \
          -e secret_db_url="${{ secrets.SECRET_DB_URL}}" \
          -e secret_db_username="${{ secrets.SECRET_DB_USERNAME}}" \
          -e secret_db_password="${{ secrets.SECRET_DB_PASSWORD}}" \
          -e secret_security_jwtExpTime="${{ secrets.SECRET_SECURITY_JWTEXPTIME}}" \
          -e secret_security_jwtSecretKey="${{ secrets.SECRET_SECURITY_JWTSECRETKEY}}" \
          --name periodapp \
          -p 8890:8890 \
          jerrywise97/periodapp:latest'

          
